// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'xs.bindings', kind: "module", path: './xs/bindings.html', attributes: []},
{name: 'xs', kind: "module", path: './xs.html', attributes: []},
];
